name: bga_issue_blog
description: Flutter 抓取 GitHub 上的 Issues，结合 GitHub Pages 搭建个人博客站点，支持 GitHub 登录和评论

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  json_annotation: ^3.0.0

  transparent_image: ^1.0.0

  url_launcher: ^5.1.4 # https://pub.flutter-io.cn/packages/url_launcher

  dio: ^3.0.3 # https://github.com/flutterchina/dio

  flutter_html: ^0.11.0 # https://github.com/Sub6Resources/flutter_html
  markdown: ^2.1.1 # https://github.com/dart-lang/markdown

  flutter_markdown: ^0.2.0 # https://github.com/flutter/flutter_markdown

dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^3.2.2 # 可以配置别名 alias genjson="flutter packages pub run build_runner build"
  flutter_test:
    sdk: flutter

  http_server: ^0.9.8+3 # https://pub.flutter-io.cn/packages/http_server

flutter:
  uses-material-design: true
  assets:
    - images/favicon.ico
    - images/no-data.png

    - images/enter-icon.svg
    - images/next-page-hover.png
    - images/next-page-normal.png
    - images/pre-page-hover.png
    - images/pre-page-normal.png

    - images/git.png
    - images/github.png
    - images/qq-group.png
